buildConfiguration:
  buildCommand: npm run build
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: ":"

staticRoutes:
  - from: /index.html
    to: /static.html
    status: 301

# dynamicRoutes:
#   - from: /index.html
#     to: /us.html
#     status: 302